/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreatepostRouteImport } from './routes/createpost'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'
import { Route as PoliciesUseragreementRouteImport } from './routes/policies/useragreement'
import { Route as PoliciesPrivacypolicyRouteImport } from './routes/policies/privacypolicy'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatepostRoute = CreatepostRouteImport.update({
  id: '/createpost',
  path: '/createpost',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesUseragreementRoute = PoliciesUseragreementRouteImport.update({
  id: '/policies/useragreement',
  path: '/policies/useragreement',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesPrivacypolicyRoute = PoliciesPrivacypolicyRouteImport.update({
  id: '/policies/privacypolicy',
  path: '/policies/privacypolicy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/createpost': typeof CreatepostRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/policies/privacypolicy': typeof PoliciesPrivacypolicyRoute
  '/policies/useragreement': typeof PoliciesUseragreementRoute
  '/posts/$postId': typeof PostsPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/createpost': typeof CreatepostRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/policies/privacypolicy': typeof PoliciesPrivacypolicyRoute
  '/policies/useragreement': typeof PoliciesUseragreementRoute
  '/posts/$postId': typeof PostsPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/createpost': typeof CreatepostRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/policies/privacypolicy': typeof PoliciesPrivacypolicyRoute
  '/policies/useragreement': typeof PoliciesUseragreementRoute
  '/posts/$postId': typeof PostsPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/createpost'
    | '/login'
    | '/profile'
    | '/signup'
    | '/policies/privacypolicy'
    | '/policies/useragreement'
    | '/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/createpost'
    | '/login'
    | '/profile'
    | '/signup'
    | '/policies/privacypolicy'
    | '/policies/useragreement'
    | '/posts/$postId'
  id:
    | '__root__'
    | '/'
    | '/createpost'
    | '/login'
    | '/profile'
    | '/signup'
    | '/policies/privacypolicy'
    | '/policies/useragreement'
    | '/posts/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreatepostRoute: typeof CreatepostRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  PoliciesPrivacypolicyRoute: typeof PoliciesPrivacypolicyRoute
  PoliciesUseragreementRoute: typeof PoliciesUseragreementRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/createpost': {
      id: '/createpost'
      path: '/createpost'
      fullPath: '/createpost'
      preLoaderRoute: typeof CreatepostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/useragreement': {
      id: '/policies/useragreement'
      path: '/policies/useragreement'
      fullPath: '/policies/useragreement'
      preLoaderRoute: typeof PoliciesUseragreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/privacypolicy': {
      id: '/policies/privacypolicy'
      path: '/policies/privacypolicy'
      fullPath: '/policies/privacypolicy'
      preLoaderRoute: typeof PoliciesPrivacypolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatepostRoute: CreatepostRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  PoliciesPrivacypolicyRoute: PoliciesPrivacypolicyRoute,
  PoliciesUseragreementRoute: PoliciesUseragreementRoute,
  PostsPostIdRoute: PostsPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
